openapi: 3.0.0
info:
    title: Express App Template
    description: app template
    version: 1.0.0
servers:
    - url: 'http://localhost:3000'
    - url: 'http://localhost:5000'
paths:
    /healthcheck:
        get:
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rs'

components:
    schemas:
        rs:
            type: object
            properties:
                metadata:
                    type: object
                    properties:
                        transactionId:
                            type: string
                        message:
                            type: string
                data:
                    type: object